version: 2
jobs:
  build:
    branch:
      only:
        newbuild
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1000m
      TERM: dumb
    steps:
      - checkout
      - run: |
          mkdir plugins
          BRANCH=newmaven
          BASE_VERSION=$(curl -s "https://circleci.com/api/v1.1/project/github/Dexels/dexels-base?circle-token=${CIRCLE_TOKEN}&limit=100&offset=0&filter=successful" | jq '[.[]| select(.workflows.job_name == "build")][0].build_num')
          NAVAJO_VERSION=$(curl -s "https://circleci.com/api/v1.1/project/github/Dexels/navajo?circle-token=${CIRCLE_TOKEN}&limit=1&offset=0&filter=successful" | jq '[.[]| select(.branch == "newmaven")][0].build_num')
          ENTERPRISE_VERSION=$(curl -s "https://circleci.com/api/v1.1/project/github/Dexels/enterprise?circle-token=${CIRCLE_TOKEN}&limit=1&offset=0&filter=successful" | jq '[.[]| select(.branch == "newmaven")][0].build_num')
          echo "versions: $BASE_VERSION - $NAVAJO_VERSION - ${ENTERPRISE_VERSION}"
          curl -s "https://${NAVAJO_VERSION}-4423334-gh.circle-artifacts.com/0/navajo_p2.zip?circle-token=$CIRCLE_TOKEN&branch=${BRANCH}" -o navajo_p2.zip
          curl -s "https://${NAVAJO_VERSION}-4423334-gh.circle-artifacts.com/0/streams_p2.zip?circle-token=$CIRCLE_TOKEN&branch=${BRANCH}" -o streams_p2.zip
          curl -s "https://${ENTERPRISE_VERSION}-4423339-gh.circle-artifacts.com/0/enterprise_p2.zip?circle-token=$CIRCLE_TOKEN&branch=${BRANCH}"  -o enterprise_p2.zip
          curl -s "https://${BASE_VERSION}-190362472-gh.circle-artifacts.com/0/dexels-base.tgz" -o unpack/dexels_base.tgz
          ls *.zip | xargs -I '{}' unzip -o '{}'
          rm -rf artifacts.* content.* features* *.index
          rm -f plugins/*tipi*
          rm *.zip
          tar xfz unpack/dexels_base.tgz --directory unpack
          rm unpack/dexels_base.tgz
          cp plugins/* unpack/bundle/
          cp run.sh unpack/          
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  package_navajo:
    machine:
      image: circleci/classic:edge
    steps:
      - attach_workspace:
          at: ~/repo
      - run: |
          docker --version
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          TAG=${MINORTAG}.$CIRCLE_BUILD_NUM
          BASE_VERSION=$(curl -s "https://circleci.com/api/v1.1/project/github/Dexels/dexels-base?circle-token=${CIRCLE_TOKEN}&limit=1&offset=0&filter=successful" | jq '.[0].build_num')
          echo "Building tag: $TAG"
          cd ~/repo
          ls -l
          docker build --build-arg TAG=${MINORTAG}.${BASE_VERSION} -t dexels/navajo-container:$TAG -t dexels/navajo-container:latest .
          docker push dexels/navajo-container:$TAG
          docker push dexels/navajo-container:latest
          curl -X POST --header "Content-Type: application/json" -d '{"branch":"master"}' "https://circleci.com/api/v1.1/project/github/dexels/navajo-sportlink/build?circle-token=${CIRCLE_TOKEN}"
          curl -X POST --header "Content-Type: application/json" -d '{"branch":"master"}' "https://circleci.com/api/v1.1/project/github/sendrato/navajo-evntzapp/build?circle-token=${CIRCLE_TOKEN}"
          curl -X POST --header "Content-Type: application/json" -d '{"branch":"master"}' "https://circleci.com/api/v1.1/project/github/Dexels/navajo.example/build?circle-token=${CIRCLE_TOKEN}"
workflows:
  version: 2
  workflow:
    jobs:
      - package_navajo:
          requires:
            - build
      - build
